defaults:
  - model: dofa_cls
  - dataset: senbench_eurosats2
  - _self_


# Training parameters
lr: 1e-3
batch_size: 64
weight_decay: 0.0001
num_workers: 8
pin_mem: true
num_gpus: 1
strategy: ddp
epochs: 50
warmup_epochs: 0
seed: 0
output_dir: ./output_dir
task: classification
resume: null
wandb_project: copernicus-bench

