defaults:
  - base_dataset

dataset_type: cobench_dfc2020_s12
task: segmentation
dataset_name: cobench_dfc2020_s1
num_classes: 8 # origin 10 but 2 not present
num_channels: 2
data_path: ${oc.env:DATASETS_DIR}/copernicusbench/dfc2020_s1s2
modality: s1
band_names: ['VV', 'VH']
band_wavelengths: [50000000, 50000000]
band_bandwidths: [1e9, 1e9]
band_stats: # null
  mean: [-12.548, -20.192]
  std: [5.257, 5.912]
image_resolution: 256
multilabel: false
ignore_index: 255
language_embed: null
input_mode: spectral
kernel_size: 16
key: null # only valid for non-spectral variables