defaults:
  - base_model

model_type: croma
task: changedetection
size: base
modality: SAR
image_resolution: 120
embed_dim: 768
pretrained_path: "CROMA_base.pt"
num_channels: 2
out_features: true
freeze_backbone: true