defaults:
  - base_model

model_type: dofa
task: classification
dofa_size: dofa_base
image_resolution: 224
embed_dim: 768
pretrained_path: "DOFA_ViT_base_e100.pth"
full_finetune: false
out_features: true