defaults:
  - base_model

model_type: softcon
task: segmentation
size: base
modality: SAR
image_resolution: 224
embed_dim: 768
pretrained_path: "B2_vitb14_softcon.pth"
num_channels: 2
out_features: true
freeze_backbone: true