defaults:
  - base_model

model_type: vit
task: regression
vit_size: base #small
#image_resolution: 224
embed_dim: 768 #384
pretrained_path: null
out_features: true
full_finetune: false
freeze_backbone: true
