defaults:
  - base_dataset

dataset_type: cobench_flood_s1
task: changedetection
dataset_name: cobench_flood_s1
num_classes: 3 # ignore cls id 3
num_channels: 2 # 3 s1 images, 2 pre, 1post: here we use 1 pre 1post for change detection
data_path: ${oc.env:DATASETS_DIR}/copernicusbench/flood_s1
modality: s1
band_names: ['VV', 'VH']
band_stats: # null
  #mean: [-12.548, -20.192, -12.548, -20.192, -12.548, -20.192]
  #std: [5.257, 5.912, 5.257, 5.912, 5.257, 5.912]
  mean: [0.0981, 0.0253, 0.0981, 0.0253] # mean on the small train split
  std: [0.0430, 0.0174, 0.0981, 0.0253] # std on the small train split
image_resolution: 224
multilabel: false
ignore_index: 3