defaults:
  - base_dataset

dataset_type: cobench_bigearthnet_s12
task: classification
dataset_name: cobench_bigearthnet_s1
num_classes: 19
num_channels: 2
data_path: ${oc.env:DATASETS_DIR}/copernicusbench/bigearthnet_s1s2
modality: s1
band_names: ['VV', 'VH']
band_stats:
  mean: [-12.548, -20.192]
  std: [5.257, 5.912]
  # mean: [-23.062, -32.016]
  # std: [21.028, 23.648]
norm_form: softcon
image_resolution: 224
multilabel: true
ignore_index: null